#! /bin/sh
set -e
target=diffprep
cleanup() {
	local rc; rc=$?
	test -n "$TD" && rm -r -- "$TD"
	test $rc = 0 || echo "$0 failed!" >& 2
}
TD=
trap cleanup 0

redir_output() {
	local target; target=$1; shift
	"$@" > "$target"
}

run() {
	"$@" && return
	{
		echo "There was a problem executing the following command:"
		echo ">>>$*<<<"
		echo "Examine, then 'exit' to quit."
	} >& 2
	xterm -e "$SHELL" -l
	false || exit
}

verbose=true
while getopts q opt
do
	case $opt in
		q) verbose=false;;
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`
test $# != 0
make -s -- "$target"
test -f "$target"
test -x "$target"
TD=`mktemp -d -- "${TMPDIR:-/tmp}/${0##*/}.XXXXXXXXXX"`
for f
do
	test -f "$f"
	# For examiner's sake.
	$verbose && echo "Test case '$f':" >& 2
	printf '%s\n' "$f" > "$TD"/origin
	cat "$f" > "$TD"/from
	cp -p -- "$target" "$TD"/
	for modes in bB xX baB xaX wW cC
	do
		into=${modes%?}
		back=${modes#"$into"}
		$verbose && printf %s "Options -$into" >& 2
		run ./"$target" -$into "$TD"/from > "$TD"/into
		$verbose && printf %s " and -$back" >& 2
		run redir_output "$TD"/back ./"$target" -$back < "$TD"/into
		set cmp -s -- ""$TD"/back" "$f"
		if "$@"
		then
			echo " passed."
		else
			echo " FAILED!"
			run "$@"; false || exit
		fi
	done
done
echo "All tests passed!" >& 2
